### ISSUE TITLE
I can't install the game

### ISSUE THREAD

**Issue by Rilabug** [AridityTeam/BetaFortressClient-Releases#1]
I open the client, I try to install the game, and it crashes the client

**Comment by Rilabug** [comment]
[bfclient.BetaFortressTeam.exception.log](https://github.com/user-attachments/files/16356441/bfclient.BetaFortressTeam.exception.log)

**Comment by Rilabug** [comment]
please fix practice.

**Comment by GrubPL** [comment]
practice is no longer doin coding stuff right now, did you see the discord, in short, he went to touch grass and enjoy his life i guess

**Comment by Rilabug** [comment]
go eat a computer

**Comment by universe-breaker** [comment]
i also cant install the game

**Comment by PracticeMedicine03** [comment]
this is just an issue with the prev version

**Comment by Rilabug** [comment]
thanks practice! i am the RED Spy!
